# Numpy

Hoje, vamos começara ver a biblioteca matemática mais importante pro ecossistema 
científico do Python: O Numpy.

Vamos relembrar alguns conceitos

In [1]:
lista = ["a", 2, 2.4, True, [1, 3], {"a": 1}]

In [2]:
lista.append("Olá")

In [3]:
lista

['a', 2, 2.4, True, [1, 3], {'a': 1}, 'Olá']

In [4]:
a = 42.5

In [5]:
a = 'aaaaa'

In [6]:
a

'aaaaa'

A biblioteca **NumPy** _(Numerical Python)_ proporciona uma forma eficiente de armazenagem e processamento de conjuntos de dados, e é utilizada como base para a construção da biblioteca Pandas, que estudaremos a seguir.

O diferencial do Numpy é sua velocidade e eficiência, o que faz com que ela seja amplamente utilizada para computação científica e analise de dados. 

A velocidade e eficiência é possível graças à estrutura chamada **numpy array**, que é um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

In [2]:
# A gente importa o numpy sempre chamando ele de "np"
import numpy as np

In [8]:
# Vamos fazer uma comparação com uma lista de Python
py_array = [[1, 2, 3]]

print(py_array)
print(type(py_array))

[[1, 2, 3]]
<class 'list'>


In [9]:
# Uma lista com 2 dimensões é uma lista de listas
print(type(py_array[0]))

<class 'list'>


In [14]:
# Nota como o tipo da variável muda para "ndarray"
np_array = np.array(py_array)

print(np_array)
print(type(np_array))
print(np_array.dtype)

[[1 2 3]]
<class 'numpy.ndarray'>
int32


In [12]:
py_array_string = [[1, 'a', 3]]
np_array_string = np.array(py_array_string)

print(np_array_string)
print(type(np_array_string))

[['1' 'a' '3']]
<class 'numpy.ndarray'>


In [13]:
py_array_string = [['a', 2, 3]]
np_array_string = np.array(py_array_string)

print(np_array_string)
print(type(np_array_string))
print(np_array_string.dtype)

[['a' '2' '3']]
<class 'numpy.ndarray'>
<U11


In [15]:
# Mas no  numpy, um ndarray continua sendo formado de ndarrays.
print(type(np_array_string[0]))

<class 'numpy.ndarray'>


In [18]:
np_array

array([[1, 2, 3]])

In [17]:
# 3 atributos básicos pra um ndarray
print(np_array.shape) # o formato do array
print(np_array.ndim)  # quantidade de dimensões
print(np_array.dtype) # o tipo de dado dos elementos do array

(1, 3)
2
int32


In [19]:
# Diferença entre o tipo array e o tipo de dado dentro do array
print(type(np_array_string))
print(np_array_string.dtype)

<class 'numpy.ndarray'>
<U11


In [20]:
# O dtype de um array do numpy pode ser controlado na hora que a gente cria.
py_array = [1, 2, 3]

array_int = np.array(py_array, dtype=np.float64)

In [21]:
print(array_int)
print(array_int.dtype)

[1. 2. 3.]
float64


In [28]:
array_int_2 = np.array([1, 2, 3], np.float64)

In [29]:
print(array_int_2)
print(array_int_2.dtype)

[1. 2. 3.]
float64


In [26]:
# Mas quando a gente não define, ele infere a partir dos nossos dados.
py_array_2 = [1.0, 2, 3]

array_float = np.array(py_array_2)

print(array_float)
print(array_float.dtype)

[1. 2. 3.]
float64


In [27]:
# Para selecionar um elemento de uma tabela no Python e no Numpy, tem uma ligeira diferença.
print(array_float[2])

3.0


**Revisando**

In [33]:
# No Python, existe o conceito de "indexing", que é pegar elementos pelo seu índice (a sua posição)
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9] 
print(lista[0])
print(lista[3])
print(lista[-1])
print(lista[-3])

# Obs.: Lembre-se que as posições no python sempre começam a contar do zero!

1
4
9
7


In [34]:
print(lista[0]==lista[-9])

True


In [37]:
# Também existe uma forma de pegar um subconjunto da lista.
# A gente chama isso de "slicing". Nota que o último elemento não entra!
print(lista[:])
print(lista[2:3])
print(lista[2:-3])

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[3]
[3, 4, 5, 6]


In [39]:
# Podemos definir um início também pro slicing.
# Quando não colocamos nada, ele assume que o início é 0.
# No caso do fim, se não colocamos nada, ele assume que o fim é o último elemento.
print(lista[:-3])
print(lista[-3:])

[1, 2, 3, 4, 5, 6]
[7, 8, 9]


In [44]:
# O poder do slicing é que a gente pode definir diferentes tamanhos de passo.
print(lista[0:9:2])
print(lista[1:5:-1])
print(lista[-1:5:-1])

[1, 3, 5, 7, 9]
[]
[9, 8, 7]


In [45]:
# Inverter essa lista
print(lista[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1]


Também podemos aplicar o conceito do slicing no numpy

In [49]:
print(array_int)
print(array_int[2])
print(array_int[:1])
print(array_int[-1:-5:-2])

[1. 2. 3.]
3.0
[1.]
[3. 1.]


**Funções numpy**  
O numpy também tem diversas funções para facilitar criação de arrays.

In [53]:
print(np.zeros(10))
print(np.ones(5))

# Alguns spoilers
print(np.identity(4))
print(np.eye(4, 3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [55]:
# Relembrando a função range
list(range(2, 10, 2))

[2, 4, 6, 8]

In [57]:
# Também podemos fazer listas de números.
print(np.arange(2, 10, 2))
print(np.arange(10.5, 30.5, 5))

[2 4 6 8]
[10.5 15.5 20.5 25.5]


In [58]:
print(np.linspace(10, 30, 10))

[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]


# Operações Básicas

In [59]:
# Se a força do numpy é ter tudo operando como vetores, 
# então ele tem que ter operações de vetores.
vetor1 = np.arange(0, 10)
vetor2 = np.arange(0, 20, 2)

print(vetor1)
print(vetor2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [60]:
# Soma por elemento
print(vetor1 + vetor2)

[ 0  3  6  9 12 15 18 21 24 27]


In [61]:
# Multiplicação elemento por elemento
print(vetor1 * vetor2)

[  0   2   8  18  32  50  72  98 128 162]


In [63]:
# produto de matrizes (neste caso, produto escalar)
# Isso é multiplicar elemento por elemento, e depois somar
print((vetor1 * vetor2).sum())
print(vetor1 @ vetor2)

570
570


## Bora praticar!

1) Inverta um vetor (o primeiro elemento vira o último). Para testar crie um vetor a partir da seguinte lista [0, 5, 1, 9, 9, 87]

In [65]:
lista = [0, 5, 1, 9, 9, 87]
np.array(lista[::-1])

array([87,  9,  9,  1,  5,  0])

In [66]:
np_array = np.array(lista)
print(np_array[::-1])

[87  9  9  1  5  0]


2) Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [67]:
vetor_2 = np.arange(1, 22, 2)
print(vetor_2)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [68]:
print(np.arange(1, 22, 2))

[ 1  3  5  7  9 11 13 15 17 19 21]


In [69]:
array_1 = np.arange(1, 22, 1)

print(array_1)
print(array_1[::2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
[ 1  3  5  7  9 11 13 15 17 19 21]


3) Ache os índices dos elementos não-zero a partir do array [1,2,0,0,4,0]

In [70]:
vetor = np.array([1, 2, 0, 0, 4, 0])

indices = [i for i in range(len(vetor)) if vetor[i] != 0]
print(indices)

[0, 1, 4]


In [83]:
array = np.array([1, 2, 0, 0, 4, 0])
indices_nao_zero = np.where(array != 0)[0]
indices_nao_zero

array([0, 1, 4], dtype=int64)

In [79]:
np.nonzero(vetor)[0]

array([0, 1, 4], dtype=int64)

E se a gente quisesse pegar os elementos diferentes de zero?

In [84]:
vetor_3 = np.array([1, 2, 0, 0, 4, 0])

elementos_nao_zeros =[]
for elemento in vetor_3:
    if elemento != 0:
        elementos_nao_zeros.append(elemento)
print(np.array(elementos_nao_zeros))


[1 2 4]


In [85]:
vetor = np.array([1, 2, 0, 0, 4, 0])
[i for i in vetor if i != 0]

[1, 2, 4]

In [90]:
array[array != 0]

array([1, 2, 4])

4) Crie uma matriz identidade 3x3

In [91]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

5) Crie um array de 10 com valores aleatórios 

In [92]:
np.random.rand(10)

array([0.51996882, 0.94612019, 0.44717706, 0.81246741, 0.48416398,
       0.22131857, 0.52492767, 0.04411294, 0.27473254, 0.1171691 ])

In [93]:
import random

lista = []

for i in range(10):
    numero_aleratorio = random.randint(0, 100)
    lista.append(numero_aleratorio)
print(np.array(lista))

[58  6 60 69  3 33 98 70 88 52]


6) Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [94]:
aleatorios1 = np.random.rand(100)
print(max(aleatorios1), min(aleatorios1))

0.9986275670812909 0.0009551977771529163


In [98]:
array_inteiro_aleatorio = np.random.randint(1, 100, 100)
maximo = np.max(array_inteiro_aleatorio)
minimo = np.min(array_inteiro_aleatorio)
print(array_inteiro_aleatorio)
print(maximo, minimo)

[68  6 66 23 95  1 94 25 30 42 78 27  8 22 32 70 31 75 53  7 98 65 48 80
 29 92 95 78 52 62 23 14 73 49 22  3  3  9 78 14 35 43 46 59 21 20 55 96
 48 12 83 28 99 16 56 46 22  6 56  1 41  6 82 32  1 67 58 18 60 92 38 22
 22 10 32  6 80 77 72 48 24 99 53  8 58 11 36 97 85 49 39 83 64 63  5 19
 11 73 85 67]
99 1


7) Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [3]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Dimensões do array 2D
linhas = 5
colunas = 5

# Crie um array 2D com 1 na borda e 0 dentro
array_2d = np.ones((linhas, colunas), dtype=int)
array_2d[1:-1, 1:-1] = 0

# Exibição do array resultante
print(array_2d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [7]:
colunas = 3
linhas = 3

array2d = []
for i in range(linhas):
    linha = []
    for j in range(colunas):
        if i == 0 or i == linhas-1 or j == 0 or j == colunas-1:
            linha.append(1)
        else:
            linha.append(0)
    array2d.append(linha)


for linha in array2d:
    print(linha)

[1, 1, 1]
[1, 0, 1]
[1, 1, 1]


8) Crie uma matriz 5x5 com valores 1, 2, 3, 4 logo abaixo da diagonal

In [9]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [10]:
# Cria uma matriz identidade 5x5
matriz = np.eye(5, dtype=int)

# Adicione 1, 2, 3, 4 logo abaixo da diagonal
matriz[1:, :-1] = np.arange(1, 5)

# Exiba a matriz resultante
print(matriz)

[[1 0 0 0 0]
 [1 2 3 4 0]
 [1 2 3 4 0]
 [1 2 3 4 0]
 [1 2 3 4 1]]


In [11]:
matriz = np.zeros((5, 5))

for i in range(1, 5):
    matriz[i, i - 1] = i

print(matriz)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## Mini tarefa

Utilizando o numpy crie dois vetores a partir das listas ```lista_1 = [1, 2, 3, 4]``` e ```lista_2 = [12, 6, 0, 29]``` e calcule o produto escalar entre esses dois vetores. Responda no [link](https://forms.gle/oz5cHCfj5yQFWw6a9).