documentação : https://numpy.org/doc/stable/

NumPy é uma biblioteca fundamental para computação científica em Python. Ela fornece suporte para arrays multidimensionais (matrizes) e funções para operações matemáticas eficientes em grande quantidade de dados. Isso a torna uma ferramenta poderosa para processamento de dados, análise estatística, simulações numéricas e muito mais.

Aqui estão alguns exemplos dos principais usos do NumPy:


In [2]:
import numpy as np


In [3]:

"""
1. Criação de Arrays:
   NumPy permite criar arrays multidimensionais de forma eficiente. Você pode criar arrays a partir de listas ou usando funções como `numpy.array()`, `numpy.zeros()`, `numpy.ones()`, `numpy.arange()`, entre outras."""

# Criando um array unidimensional
array1d = np.array([1, 2, 3, 4, 5])

# Criando um array bidimensional (matriz)
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [18]:
"""
2. Operações Matemáticas:
   NumPy permite realizar operações matemáticas em arrays de forma eficiente, seja elemento a elemento ou entre arrays."""


array = np.array([1, 2, 3, 4, 5])

# Operações element-wise
resultado = array + 10
resultado = np.sin(array)
resultado = array * 2

# Operações entre arrays
outro_array = np.array([5, 4, 3, 2, 1])
resultado = array + outro_array
print(resultado)

[6 6 6 6 6]


In [20]:

"""3. Indexação e Fatiamento:
   Assim como listas em Python, você pode acessar elementos individuais e fatiar arrays do NumPy."""


array = np.array([10, 20, 30, 40, 50])

primeiro_elemento = array[0]
print(primeiro_elemento)
subarray = array[1:4]
print(subarray)

10
[20 30 40]


In [24]:
"""
4. Funções Estatísticas:
   NumPy oferece várias funções para análise estatística de dados."""
array = np.array([10, 20, 30, 40, 50])

media = np.mean(array)
desvio_padrao = np.std(array)
valor_maximo = np.max(array)
print(media, desvio_padrao, valor_maximo)


30.0 14.142135623730951 50


In [27]:
"""5. Álgebra Linear:
   NumPy é amplamente usado em álgebra linear, com suporte para multiplicação de matrizes, decomposições, resolução de sistemas lineares, entre outros."""

matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

produto = np.dot(matriz1, matriz2)
solucao_sistema = np.linalg.solve(matriz1, matriz2)
print(solucao_sistema)
"""Esses são apenas alguns exemplos dos principais usos da biblioteca NumPy em Python. Ela é uma ferramenta essencial para cientistas de dados, engenheiros e pesquisadores que trabalham com análise numérica e processamento de dados."""


[[-3. -4.]
 [ 4.  5.]]


'Esses são apenas alguns exemplos dos principais usos da biblioteca NumPy em Python. Ela é uma ferramenta essencial para cientistas de dados, engenheiros e pesquisadores que trabalham com análise numérica e processamento de dados.'

In [26]:
#Multiplicação de Matrizes:

matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

produto = np.dot(matriz1, matriz2)

print(produto)

[[19 22]
 [43 50]]


In [28]:
# Transposição de Matrizes:
matriz = np.array([[1, 2], [3, 4]])
matriz_transposta = matriz.T
print(matriz_transposta)

[[1 3]
 [2 4]]


In [29]:
#Determinante e Inversa:

matriz = np.array([[1, 2], [3, 4]])
determinante = np.linalg.det(matriz)
matriz_inversa = np.linalg.inv(matriz)
print(determinante)
print(matriz_inversa)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


Manipulação de Dados:
O NumPy oferece muitas ferramentas para manipular e transformar seus dados de maneira eficiente:



In [13]:
#Redimensionamento e Reshape:

array = np.array([1, 2, 3, 4, 5, 6])
matriz = array.reshape(2, 3)

In [14]:
#Empilhamento de Arrays:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
empilhados = np.vstack((array1, array2))

Operações Estatísticas e de Agregação: Operações Estatísticas e de Agregação:

In [15]:
#Cálculos Estatísticos:
dados = np.array([10, 20, 30, 40, 50])
media = np.mean(dados)
mediana = np.median(dados)
desvio_padrao = np.std(dados)

In [16]:
#Soma, Mínimo e Máximo:
array = np.array([10, 20, 30, 40, 50])
soma_total = np.sum(array)
valor_minimo = np.min(array)
valor_maximo = np.max(array)

Geração de Dados Aleatórios:

NumPy oferece funções para geração de dados aleatórios para simulações e experimentos:

In [17]:
# Geração de números aleatórios entre 0 e 1
aleatorios = np.random.rand(5)

# Geração de matriz de números inteiros aleatórios
matriz_aleatoria = np.random.randint(0, 10, size=(3, 3))



**Usos comuns de Arrays Tridimensionais:**

1. **Imagens 3D:** Um array tridimensional pode representar uma imagem colorida em três canais (RGB) ou volumes de imagem em aplicações médicas.

2. **Dados Espaciais:** Em aplicações de geociência ou simulações físicas, arrays tridimensionais podem representar dados espaciais em três dimensões.

3. **Vídeo em 3D:** Em processamento de vídeo, arrays tridimensionais podem ser usados para representar sequências de quadros de vídeo em três dimensões.

4. **Dados Temporais:** Em análises financeiras ou científicas, arrays tridimensionais podem representar dados ao longo do tempo, combinando informações temporais e espaciais.

5. **Modelagem Matemática:** Em simulações numéricas complexas, arrays tridimensionais podem representar campos tridimensionais, como fluxo de fluidos ou campos elétricos.

6. **Dados de Sensores:** Em aplicações de IoT ou engenharia, arrays tridimensionais podem representar dados coletados de sensores em três dimensões.

7. **Visualização 3D:** Arrays tridimensionais podem ser usados para visualização de dados em 3D, como modelagem molecular ou visualização de gráficos tridimensionais.

Esses são apenas alguns exemplos de como os arrays tridimensionais podem ser úteis em análises de dados usando a biblioteca NumPy em Python. Eles são especialmente valiosos quando os dados possuem uma dimensão extra que adiciona contexto ou informações importantes para a análise.

In [30]:
import numpy as np

# Criando um array tridimensional 3x4x5 com valores aleatórios entre 0 e 9
array_tridimensional = np.random.randint(10, size=(3, 4, 5))
print("Array Tridimensional:")
print(array_tridimensional)

# Acessando elementos específicos do array
elemento = array_tridimensional[1, 2, 3]
print(f"Elemento na posição (1, 2, 3): {elemento}")

# Slicing (fatiamento) do array
subarray = array_tridimensional[0:2, 1:3, 2:4]
print("Subarray:")
print(subarray)

# Algumas operações de agregação
soma_total = np.sum(array_tridimensional)
media = np.mean(array_tridimensional)
maximo = np.max(array_tridimensional)
minimo = np.min(array_tridimensional)

print(f"Soma Total: {soma_total}")
print(f"Média: {media}")
print(f"Máximo: {maximo}")
print(f"Mínimo: {minimo}")


Array Tridimensional:
[[[4 7 0 1 1]
  [4 0 2 0 3]
  [2 3 7 6 3]
  [6 9 9 1 0]]

 [[1 5 0 1 6]
  [2 3 8 6 4]
  [2 4 7 0 0]
  [4 6 3 7 4]]

 [[4 7 0 9 6]
  [7 3 2 6 2]
  [2 8 5 1 1]
  [7 9 2 1 5]]]
Elemento na posição (1, 2, 3): 0
Subarray:
[[[2 0]
  [7 6]]

 [[8 6]
  [7 0]]]
Soma Total: 228
Média: 3.8
Máximo: 9
Mínimo: 0
